variables:
  projectBase:     './SentenceTransformers/SentenceTransformers.csproj'
  projectMiniLM:   './SentenceTransformers.MiniLM/SentenceTransformers.MiniLM.csproj'
  projectArticXs:  './SentenceTransformers.ArticXs/SentenceTransformers.ArticXs.csproj'
  buildConfiguration: 'Release'
  targetVersion: yy.M.$(build.buildId)
  
pool:
  vmImage: 'windows-latest'

trigger:
- main

steps:
- checkout: self
  submodules: true
  fetchDepth: 10
  
- task: PowerShell@2
  displayName: 'Create CalVer Version'
  inputs:
    targetType: 'inline'
    script: |
      $dottedDate = (Get-Date).ToString("yy.M")
      $buildID = $($env:BUILD_BUILDID) 
      $newTargetVersion = "$dottedDate.$buildID"
      Write-Host "##vso[task.setvariable variable=targetVersion;]$newTargetVersion"
      Write-Host "Updated targetVersion to '$newTargetVersion'"

- task: UseDotNet@2
  displayName: 'Use .NET 8.0 SDK'
  inputs:
    packageType: sdk
    version: 8.x
    includePreviewVersions: false
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'restore nuget'
  inputs:
    command: 'restore'
    projects: '$(project)'


- task: DotNetCoreCLI@2
  displayName: 'build base project'
  inputs:
    command: 'build'
    projects: '$(projectBase)'
    arguments: '-c $(buildConfiguration) /p:Version=$(targetVersion)  /p:GeneratePackageOnBuild=true'

- task: NuGetCommand@2
  displayName: 'push base package first'
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build MiniLM project'
    projects: '$(projectMiniLM)'
    arguments: '-c $(buildConfiguration) /p:Version=$(targetVersion)  /p:GeneratePackageOnBuild=true'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build ArticXS project'
    projects: '$(projectArticXs)'
    arguments: '-c $(buildConfiguration) /p:Version=$(targetVersion)  /p:GeneratePackageOnBuild=true'

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '**/SentenceTransformers.*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity-org'
